export const TREE_STAGES = [
  {
    name: 'New Seed',
    minHours: 0,
    description: 'A tiny seed filled with potential. Your journey begins here!',
    image: '/Trees/stage_1-removebg-preview.png',
    message: 'Welcome! Your ministry is like a seed. Keep sprinkling it with your efforts.',
  },
  {
    name: 'First Sprout',
    minHours: 50,
    description: 'A small green sprout has emerged! Your dedication is starting to show.',
    image: '/Trees/stage_2-removebg-preview.png',
    message: 'Look at that! 50 hours already. Your seedling is healthy and growing.',
  },
  {
    name: 'Growing Sapling',
    minHours: 100,
    description: 'A delicate sapling reaching for the light. Your roots are deepening.',
    image: '/Trees/stage_3-removebg-preview.png',
    message: '100 hours! You\'re building a steady rhythm in your service.',
  },
  {
    name: 'Strong Stem',
    minHours: 150,
    description: 'The stem is thickening, preparing to support more branches.',
    image: '/Trees/stage_4-removebg-preview.png',
    message: '150 hours! You are becoming more resilient and committed.',
  },
  {
    name: 'Branching Out',
    minHours: 200,
    description: 'New branches are appearing! You\'re reaching more people than ever.',
    image: '/Trees/stage_5-removebg-preview.png',
    message: '200 hours! Like these branches, your influence is expanding.',
  },
  {
    name: 'Lush Greenery',
    minHours: 250,
    description: 'Leaves are filling out, creating a beautiful canopy of service.',
    image: '/Trees/Stage_6-removebg-preview.png',
    message: '250 hours! Your consistency is creating a beautiful legacy.',
  },
  {
    name: 'Sturdy Young Tree',
    minHours: 300,
    description: 'A strong young tree that can weather any storm. Halfway to the goal!',
    image: '/Trees/stage_7-removebg-preview.png',
    message: '300 hours! Halfway there! You are a pillar of strength in the congregation.',
  },
  {
    name: 'Blossoming Hope',
    minHours: 350,
    description: 'Tiny blossoms are appearing. Your hard work is bearing fruit.',
    image: '/Trees/stage_8-removebg-preview.png',
    message: '350 hours! Your ministry is truly blossoming. Keep up the great work!',
  },
  {
    name: 'Fruitful Witness',
    minHours: 400,
    description: 'The tree is now bearing fruit. Your service is truly rewarding.',
    image: '/Trees/stage_9-removebg-preview.png',
    message: '400 hours! You are seeing the fruits of your labor. How encouraging!',
  },
  {
    name: 'Golden Harvest',
    minHours: 450,
    description: 'A tree heavy with ripe fruit. A season of great productivity!',
    image: '/Trees/stage_10-removebg-preview.png',
    message: '450 hours! You are in a season of great spiritual harvest.',
  },
  {
    name: 'Majestic Presence',
    minHours: 500,
    description: 'A grand, majestic tree providing shade for many. An inspiration to all.',
    image: '/Trees/stage_11-removebg-preview.png',
    message: '500 hours! You are a truly majestic example of faithfulness.',
  },
  {
    name: 'Eternal Flourish',
    minHours: 550,
    description: 'A fully matured, flourishing tree. You\'ve reached the pinnacle of growth!',
    image: '/Trees/stage_12-removebg-preview.png',
    message: '550 hours! Your ministry is a beautiful example of consistency.',
  },
  {
    name: 'Legendary Legacy',
    minHours: 600,
    description: 'The ultimate form of your spiritual tree. A legacy that will last forever.',
    image: '/Trees/stage_13-removebg-preview.png',
    message: '600+ hours! You have achieved the highest possible growth. You are a Legend!',
  },
];
